Vagrant.configure("2") do |config|
	(1..2).each do |i|
		config.vm.define "node#{i}" do |node|
			# 设置虚拟机的box
			node.vm.box = "centos/7"
			
			# 设置虚拟机主机名
			node.vm.hostname = "node#{i}"

			# 设置虚拟机的虚拟ip
			node.vm.network "private_network", ip: "192.168.10.#{10+i}"
			
			# 设置vm的相关配置
			#
			node.vm.provider "virtualbox" do |v|

				# 设置虚拟机的名称
				#
				v.name = "node#{i}"
				
				# 设置虚拟机的内存和cpu
				v.memory = 2048
				v.cpus = 1
			end
		end
	end
end
